[package]
name = "file_converter"
version = "0.1.0"
edition = "2024"

[lib]
name = "file_converter"
crate-type = ["cdylib", "rlib"]

[dependencies]
image = "0.25.8"
pdfium-render = "0.8.35"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.54"
console_error_panic_hook = "0.1.7"
lopdf = "0.38.0"
flate2 = "1.1.4"
getrandom = { version = "0.3", features = ["wasm_js"] }
